apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-update
    app: update from git
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
